### ISSUE TITLE
Can't upload file

### ISSUE THREAD

**Issue by andrewleech** [andrewleech/PyWebDAV3#1]
When trying to copy a file onto the server from mac, Finder as the client.
Gives error, creates zero byte file.
----------------------------------------
Exception happened during processing of request from ('<snip>', 64387)
Traceback (most recent call last):
<snip> - - [29/Jul/2016 07:35:07] "PROPFIND /devpi8/upload/PyWebDAV3-0.9.8/pywebdav/server/._daemonize.py HTTP/1.1" 404 -
  File "/usr/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 415, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 403, in handle_one_request
    method()
  File "virtualenv_linux/lib/python3.5/site-packages/pywebdav/lib/locks.py", line 141, in do_LOCK
    {'Lock-Token' : '<opaquelocktoken:%s>' % token})
  File "virtualenv_linux/lib/python3.5/site-packages/pywebdav/lib/WebDAVServer.py", line 65, in send_body
    self.send_response(code, message=msg)
  File "/usr/lib/python3.5/http/server.py", line 471, in send_response
    self.send_response_only(code, message)
  File "/usr/lib/python3.5/http/server.py", line 486, in send_response_only
    (self.protocol_version, code, message)).encode(
TypeError: %d format: a number is required, not str
----------------------------------------

**Comment by auyeung112002** [comment]
Also encounter the same error. Using Builtin file explorer of Windows 10

**Comment by gbach** [comment]
The same here (explorer on win10)
