### ISSUE TITLE
Package meta is missing dependency

### ISSUE THREAD

**Issue by nicktime** [andrewleech/PyWebDAV3#11]
```
$ sudo pip install PyWebDAV3
[sudo] password for nick: 
The directory '/home/nick/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nick/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting PyWebDAV3
  Downloading https://files.pythonhosted.org/packages/9d/77/1115b1ec5861ced542373b63551febe9e35bf69c8145680625d9f88be2dd/PyWebDAV3-0.9.12.tar.gz (519kB)
    100% |████████████████████████████████| 522kB 428kB/s 
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from PyWebDAV3)
Installing collected packages: PyWebDAV3
  Running setup.py install for PyWebDAV3 ... done
Successfully installed PyWebDAV3-0.9.12
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

$ davserver
Traceback (most recent call last):
  File "/usr/local/bin/davserver", line 9, in <module>
    load_entry_point('PyWebDAV3==0.9.12', 'console_scripts', 'davserver')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/pywebdav/server/server.py", line 28, in <module>
    from pywebdav.server.fileauth import DAVAuthHandler
  File "/usr/local/lib/python2.7/dist-packages/pywebdav/server/fileauth.py", line 32, in <module>
    from .fshandler import FilesystemHandler
  File "/usr/local/lib/python2.7/dist-packages/pywebdav/server/fshandler.py", line 3, in <module>
    import html
ImportError: No module named html

```

**Comment by a-detiste** [comment]
Maybe (broken) Python2 support should be removed
