### ISSUE TITLE
use nginx proxy_pass，when get file  will cause an error

### ISSUE THREAD

**Issue by arschlochnop** [andrewleech/PyWebDAV3#15]
nginx conf 
```
upstream testweb{
        server test.com max_fails=3; 
        keepalive 16;
        }
server {

        listen      443;
        server_name  domain.com;
        ssl on;
        ssl_certificate /usr/local/nginx/ssl/fullchain.key.pem;
        ssl_certificate_key /usr/local/nginx/ssl/privkey.key;
       location / {
	    proxy_pass http://testweb;
      }
```
webdav server 
> test.com

command
> davserver -D D:\webdavserver -n -J -v  -l INFO -H 0.0.0.0

When get webdav file,error info
![image](https://user-images.githubusercontent.com/7948693/62887913-d3dd6700-bd70-11e9-9822-9af501287f6f.png)

```
Exception happened during processing of request from ('xxx.xxx.xxx.xx', 48906)
Traceback (most recent call last):
  File "X:\cmder\vendor\python3\Lib\socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "X:\cmder\vendor\python3\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "X:\cmder\vendor\python3\Lib\socketserver.py", line 696, in __init__
    self.handle()
  File "X:\cmder\vendor\python3\Lib\http\server.py", line 420, in handle
    self.handle_one_request()
  File "X:\cmder\vendor\python3\Lib\http\server.py", line 386, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "X:\cmder\vendor\python3\Lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054]
```

**Comment by arschlochnop** [comment]
solution：

use command  `-T` option
you can close `http_response_use_iterator` and `chunked_http_response`  to solve the above problem

but there is still a problem with this.   :(
The program cannot correctly identify the type of responed data, error info:

when get text file 
```
Traceback (most recent call last):
  File "X:\cmder\vendor\python3\Lib\socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "X:\cmder\vendor\python3\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "X:\cmder\vendor\python3\Lib\socketserver.py", line 696, in __init__
    self.handle()
  File "X:\cmder\vendor\python3\Lib\http\server.py", line 418, in handle
    self.handle_one_request()
  File "X:\cmder\vendor\python3\Lib\http\server.py", line 406, in handle_one_request
    method()
  File "D:\Code\python3\webdavserver\pywebdav\lib\WebDAVServer.py", line 292, in do_GET
    status_code = self._HEAD_GET(with_body=True)
  File "D:\Code\python3\webdavserver\pywebdav\lib\WebDAVServer.py", line 277, in _HEAD_GET
    content_type, headers)
  File "D:\Code\python3\webdavserver\pywebdav\lib\WebDAVServer.py", line 121, in send_body_chunks_if_http11
    self.send_body_chunks(DATA, code, msg, desc, ctype, headers)
  File "D:\Code\python3\webdavserver\pywebdav\lib\WebDAVServer.py", line 188, in send_body_chunks
    self.wfile.write(DATA.read())
  File "X:\cmder\vendor\python3\Lib\socketserver.py", line 775, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'
```
get directory：
```
Traceback (most recent call last):
  File "X:\cmder\vendor\python3\Lib\socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "X:\cmder\vendor\python3\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "X:\cmder\vendor\python3\Lib\socketserver.py", line 696, in __init__
    self.handle()
  File "X:\cmder\vendor\python3\Lib\http\server.py", line 418, in handle
    self.handle_one_request()
  File "X:\cmder\vendor\python3\Lib\http\server.py", line 406, in handle_one_request
    method()
  File "D:\Code\python3\webdavserver\pywebdav\lib\WebDAVServer.py", line 292, in do_GET
    status_code = self._HEAD_GET(with_body=True)
  File "D:\Code\python3\webdavserver\pywebdav\lib\WebDAVServer.py", line 277, in _HEAD_GET
    content_type, headers)
  File "D:\Code\python3\webdavserver\pywebdav\lib\WebDAVServer.py", line 119, in send_body_chunks_if_http11
    self.send_body(DATA, code, msg, desc, ctype, headers)
  File "D:\Code\python3\webdavserver\pywebdav\lib\WebDAVServer.py", line 110, in send_body
    self.wfile.write(DATA)
  File "X:\cmder\vendor\python3\Lib\socketserver.py", line 775, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'Resource'
```
And more error.

fix problems:
> pywebdav\lib\WebDAVServer.py
modify line 99 -107
```
        if DATA:
            if isinstance(DATA, str) or isinstance(DATA, six.text_type)or isinstance(DATA, bytes):
                log.debug("Don't use iterator")
                self.wfile.write(DATA)
            else:
                if self._config.DAV.getboolean('http_response_use_iterator'):
                    # Use iterator to reduce using memory
                    log.debug("Use iterator")
                    for buf in DATA:
                        self.wfile.write(buf)
                        self.wfile.flush()
                else:
                    # Don't use iterator, it's a compatibility option
                    log.debug("Don't use iterator")
                    res = DATA.read()
                    if isinstance(res,bytes):
                        self.wfile.write(res)
                    else:
                        self.wfile.write(res.encode('utf8'))
        return None
```

**Comment by andrewleech** [comment]
Hey thanks for the details, and good job figuring out the problem.

I don't actually use this myself any more, but if you can put your change in a merge request (should be able to do it via the web edit interface even) I'm happy to merge it and probably the other merge request that's open, then push up a release.
